myproject/library/books/urls.py
from django.contrib import admin
from django.urls import path
from books import views
from students import views
from books import views
app_name="books"

urlpatterns = [
    path('',views.home,name="h"),
    path('addbooks',views.addbooks,name="a"),
    path('addbooks1',views.addbooks1,name="ad"),
    path('viewbooks',views.viewbooks,name="v"),
    path('detail/<int:p>',views.detail,name="detail"),
    path('edit/<int:p>',views.edit,name="edit"),
    path('delete/<int:p>',views.delete,name="delete"),
    path('factorial',views.factorial,name="f"),
    path('search',views.search,name="search"),

]

myproject/library/library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('students/',include('students.urls')),

]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myproject/library/students/urls.py
from django.contrib import admin
from django.urls import path
from books import views
from students import views
from students import views
app_name="students"

urlpatterns = [
    path('register',views.register,name="r"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
    path('viewstudent',views.viewstudent,name="vs"),

]

myproject/library/books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=20)
    author=models.CharField(max_length=20)
    price=models.IntegerField()
    pdf=models.FileField(upload_to="book/pdf")
    cover=models.ImageField(upload_to="book/images",null=True,blank=True)
    def __str__(self):
        return self.title

myproject/library/students/models.py
from django.db import models

# Create your models here.
class student(models.Model):
    name=models.CharField(max_length=20)
    age=models.IntegerField()

myproject/library/books/forms.py
from django import forms
from books.models import Book

class bookform(forms.ModelForm):
    class Meta:
         model=Book
         fields="__all__"

myproject/library/books/views.py
from books.forms import bookform
from django.db.models import Q
from django.shortcuts import render
from books.models import Book
from django.contrib.auth.decorators import login_required
# from django.http import HttpResponse

# Create your views here.
def home(request):

    return render(request,'home.html')
@login_required
def addbooks(request):
    if(request.method=="POST"):#after submission
        t=request.POST['t']
        a=request.POST['a']
        p=request.POST['p']
        f=request.FILES['f']
        i=request.FILES['i']

        b=Book.objects.create(title=t,author=a,price=p,pdf=f,cover=i)
        b.save()
        return viewbooks(request)
    return render(request,'addbooks.html')
@login_required
def viewbooks(request):
    k = Book.objects.all()
    return render(request,'viewbooks.html',{'b':k})
@login_required
def addbooks1(request):
    if(request.method=="POST"):#after submission:
        form=bookform(request.POST)#create form object initialized with values inside request.POST
        if form.is_valid():
            form.save()#saves form object in db model Book
            return viewbooks(request)
    form=bookform()#create empty form object
    return render(request,'addbooks1.html',{'form':form})
@login_required
def factorial(request):
    if(request.method=="POST"):
        num=int(request.POST['n'])
        # return HttpResponse(num)
        f=1
        for i in range(1,num+1):
          f=f*i
        return render(request,'factorial.html',{'factorial':f})
    return render(request,'factorial.html')

def detail(request,p):

    b=Book.objects.get(id=p)
    return render(request,'bookdetail.html',{'b':b})
@login_required
def edit(request,p):
    b= Book.objects.get(id=p)

    if (request.method == "POST"):# after submission:

        form = bookform(request.POST,request.FILES,instance=b)  # create form object initialized with values inside request.POST
        if form.is_valid():
            form.save()  # saves form object in db model Book
            return viewbooks(request)

    form=bookform(instance=b)
    return render(request,'edit.html',{'form':form})

def search(request):
    b=None
    q=""
    if(request.method=="POST"):
        q=request.POST['q']
        b=Book.objects.filter(Q(title__icontains=q)| Q(author__icontains=q))
    return render(request,'search.html',{'q':q,'b':b})

@login_required
def delete(request,p):
    b=Book.objects.get(id=p)
    b.delete()
    return viewbooks(request)

myproject/library/students/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,authenticate,logout
from students.models import student
from django.contrib.auth.models import User
from django.http import HttpResponse



# Create your views here.
def register(request):
    if (request.method == "POST"):
        u=request.POST['u']
        p= request.POST['p']
        c= request.POST['c']
        e= request.POST['e']
        f= request.POST['f']
        l= request.POST['l']
        if(p==c):
           user=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
           user.save()
           return redirect('books:h')
        else:
            return HttpResponse("Password are not same")

    return render(request,'register.html')

def user_login(request):
    if(request.method=="POST"):
        n=request.POST['n']
        d=request.POST['d']
        user=authenticate(username=n,password=d)
        if user:
            login(request,user)
            return redirect('books:h')
        else:
            return HttpResponse("Invalid credentials")

    return render(request,'login.html')

def user_logout(request):
    logout(request)
    return redirect('students:login')
def viewstudent(request):
    s=student.objects.all()
    return render(request,'viewstudent.html',{'d':s})

myproject/library/templates/addbooks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <h3>Add Books</h3>
<form method="POST" enctype="multipart/form-data">
<!--    enctype using file uploading-->
    {% csrf_token %}

<div class="mb-3">
  <label class="form-label">Title</label>
  <input type="text" name="t" class="form-control" placeholder="Enter the title">
</div>
<div class="mb-3">
  <label class="form-label">Author</label>
  <input type="text" class="form-control" name="a" placeholder="Enter the author">
</div>
<div class="mb-3">
  <label class="form-label">Price</label>
  <input type="number" class="form-control" name="p" placeholder="Enter the price">
</div>
    <div class="mb-3">
  <label class="form-label">Document</label>
  <input type="file" class="form-control" name="f">
</div>
    <div class="mb-3">
  <label class="form-label">Cover</label>
  <input type="file" class="form-control" name="i">
</div>
<div class="mb-3">
    <input type="submit" class="form-control btn btn-primary">
</div>

    </form>
    </center>



{% endblock %}

myproject/library/templates/addbooks1.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <h2>Add Books Details1</h2>
    <form method="POST">
        {% csrf_token %}
        <table>
    {{form.as_table}}
            </table>
        <input type="submit">
        </form>
    </center>
{% endblock %}

myproject/library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Libraryapp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:h' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:a' %}">Add</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'books:v' %}">View Book</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:f' %}">Factorial</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'students:vs' %}">View Student</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'students:logout' %}">Logout</a>
          </li>
        {% else %}

          <li class="nav-item">
          <a class="nav-link" href="{% url 'students:r' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'students:login' %}">Login</a>
          </li>
        {% endif %}

      </ul>
      <form class="d-flex" method="POST" action="{% url 'books:search' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

myproject/library/templates/bookdetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <h2>Books Details</h2>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <td>{{b.id}}</td>
    </tr>
    <tr>
        <th>TITLE</th>
        <td>{{b.title}}</td>
    </tr>
    <tr>
        <th>AUTHOR</th>
        <td>{{b.author}}</td>
    </tr>
    <tr>
        <th>PRICE</th>
        <td>{{b.price}}</td>
    </tr>
    <tr>
        <th>COVER</th>
        <td><img src="{{b.cover.url}}" height="100px" width="100px"></td>
    </tr>
    <tr>
        <th>DOCUMENT</th>
        <td><a href="{{b.pdf.url}}">Download</a></td>
    </tr>

</table>
    </center>
{% endblock %}

myproject/library/templates/edit.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <h2>Add Books Details1</h2>
<form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
    {{form.as_table}}
            </table>
        <input type="submit">
        </form>
    </center>
{% endblock %}

myproject/library/templates/factorial.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <h2>Factorial</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
  <label class="form-label">Number</label>
  <input type="number" name="n" class="form-control" placeholder="Enter a number">
</div>
        <div class="mb-3">
  <input type="submit" class="form-control btn btn-primary">
</div>

        </form>
    {% if factorial %}
    <h3>Factorial is{{factorial}}</h3>
    {% endif %}
    </center>
{% endblock %}

myproject/library/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Welcome Home Page</h2>
{% if user.is_authenticated %}
<p>{{user.username}}</p>
{% else %}
<p>Guest</p>
{% endif %}
{% endblock %}

myproject/library/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3>Login</h3>

    <form method="POST" enctype="multipart/form-data">
<!--    enctype using file uploading-->
    {% csrf_token %}

<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" name="n" class="form-control" placeholder="Enter the name">
</div>
        <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="d" placeholder="Enter the password">
</div>
        <div class="mb-3">
    <input type="submit" class="form-control btn btn-primary" value="login">
</div>
    </form>
    </center>
{% endblock %}

myproject/library/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3>Register</h3>

    <form method="POST" enctype="multipart/form-data">
<!--    enctype using file uploading-->
    {% csrf_token %}

<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" name="u" class="form-control" placeholder="Enter the name">
</div>
<div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password">
</div>
<div class="mb-3">
  <label class="form-label">Confirm password</label>
  <input type="password" class="form-control" name="c" placeholder="Enter the password">
</div>
    <div class="mb-3">
  <label class="form-label">Email</label>
  <input type="text" class="form-control" name="e" placeholder="Enter a mail">
</div>
    <div class="mb-3">
  <label class="form-label">First name</label>
  <input type="text" class="form-control" name="f">
</div>
        <div class="mb-3">
  <label class="form-label">last name</label>
  <input type="text" class="form-control" name="l">
</div>
<div class="mb-3">
    <input type="submit" class="form-control btn btn-primary">
</div>

    </form>


{% endblock %}

myproject/library/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <h2>Book Details</h2>

    <h5>You have searched for query{{q}}</h5>
    {% if b %}
    <table class="table table-bordered">

    <tr><th>ID</th>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PRICE</th>
        <th>DOCUMENT</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>
    {% for i in b %}
    <tr><td>{{i.id}}</td>
        <td><a href="{{i.pdf.url}}">Download</a></td>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.price}}</td>
        <td><img src="{{i.cover.url}}" height="100px" width="100px"></td>
        <td><a href="{% url 'books:detail' i.id %}" class="btn btn-danger">View</a></td>
        <td><a href="{% url 'books:edit' i.id %}" class="btn btn-danger">Edit</a></td>
        <td><a href="{% url 'books:delete' i.id %}" class="btn btn-danger">Delete</a></td>
    </tr>

    {% endfor %}
</table>
    {% else %}
    <b><p>No results found</p></b>
    {% endif %}
    </center>
{% endblock %}

myproject/library/templates/viewbooks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>View Books</h3>
<!--{{b}}-->
<center>
<table class="table table-bordered">

    <tr><th>ID</th>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PRICE</th>
        <th>DOCUMENT</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>
    {% for i in b %}
    <tr><td>{{i.id}}</td>
        <td><a href="{{i.pdf.url}}">Download</a></td>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.price}}</td>
        <td><img src="{{i.images.url}}" height="100px" width="100px"></td>
        <td><a href="{% url 'books:detail' i.id %}" class="btn btn-danger">View</a></td>
        <td><a href="{% url 'books:edit' i.id %}" class="btn btn-danger">Edit</a></td>
        <td><a href="{% url 'books:delete' i.id %}" class="btn btn-danger">Delete</a></td>
    </tr>

    {% endfor %}
</table>
    </center>

<!--<ol>-->
<!--{% for i in b %}-->
<!--<li>Book Details</li>-->
<!--<ul>-->
<!--    <li>TITLE:{{i.title}}</li>-->
<!--    <li>AUTHOR:{{i.author}}</li>-->
<!--    <li>PRICE:{{i.price}}</li>-->
<!--</ul>-->


<!--{% endfor %}-->
<!--</ol>-->
{% endblock %}

myproject/library/templates/viewstudent.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>View Student</h3>
<ol>
    {% for i in d %}
    <li>View Students</li>
    <ul>
        <li>NAME:{{i.name}}</li>
        <li>AGE:{{i.age}}</li>
    </ul>
    {% endfor %}
</ol>


{% endblock %}